module.exports = {
   ADD_TO_CART: 'ADD_TO_CART', 
   EMPTY_CART: 'EMPTY_CART', 
   UPDATE_CART: 'UPDATE_CART',
   SEARCH_DATA: 'SEARCH_DATA',
   REMOVE_ITEM: 'REMOVE_ITEM',
   PURCHASE_MADE: 'PURCHASE_MADE',
   EDIT_ITEM: "EDIT_ITEM",
   DELETE_ITEM: 'DELETE_ITEM',
   GET_ALL_PRODUCTS: "GET_ALL_PRODUCTS"
}